swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    # binds a127 app logic to a route
    x-swagger-router-controller: login
    post:
      tags:
        - "Login"
      description: Allows the user to log in
      # used as the method name of the controller
      operationId: login
      parameters:
        - in: body
          name: loginForm
          description: login form
          required: true
          schema: 
            $ref: "#/definitions/loginForm"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralObjectResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /events:
    x-swagger-router-controller: event
    get:
      description: get the events list
      operationId: getEvents
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: add a new event to the list
      consumes:
        - application/json 
        - multipart/form-data
        - x-www-form-urlencoded
      parameters:
        - in: formData
          name: title
          type: string
          required: true
          description: Title of the event
        - in: formData
          name: description
          type: string
          required: true
          description: Description of the event
        - in: formData  
          name: place
          type: string
          required: true
          description: Place of the event
        - in: formData
          name: address
          type: string
          required: true
          description: Address of the event
        - in: formData
          name: start_date
          type: string
          required: true
          description: Start date of the event
        - in: formData
          name: finish_date
          type: string
          required: true
          description: End date of the event
        - in: formData
          name: start_time
          type: string
          required: true
          description: Start time of the event
        - in: formData
          name: finish_time
          type: string
          required: true
          description: End time of the event
        - in: formData
          name: image
          type: file
          required: true
          description: Image of the event
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/EventResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  
# complex objects have schema definitions
definitions:
  GeneralResponse:
    type: string
  GeneralObjectResponse:
    type: object
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  loginForm:
    properties:
      email:
        type: string
      password:
        type: string
  LoginResponse:
    required:
      - token
    properties:
      token:
        type: string
  EventResponse:
    type: object
    properties:
      id:
        type: number
        description: identifier
      title:
        type: string
        description: Title of the event
      description:
        type: string
        description: Description of the event
      place:
        type: string
        description: Place of the event
      address:
        type: string
        description: Address of the event
      start_date:
        type: string
        description: Start date of the event
      finish_date:
        type: string
        description: End date of the event
      start_time:
        type: string
        description: Start time of the event
      finish_time:
        type: string
        description: End time of the event
      image:
        type: string
        description: Image of the event
    required:
      - id
      - title
      - description
      - place
      - address
      - start_date
      - finish_date
      - start_time
      - finish_time
      - image
  EventListResponse:
    required:
      - events
    properties:
      events:
        type: array
        items:
          $ref: "#/definitions/EventResponse"
      
